### PR TITLE
Winston notebook for Earthquake-S&P500 price analysis + fixes to Gold

### PR DESCRIPTION
**Pull request by wel51x**
… analysis

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by chrisluedtke** [comment]
I'd like more description of what you added here. Also, delete the pull request template if you're not going to use it, since it takes up a lot of space here and on Slack.

**Comment by wel51x** [comment]
This module compares the effect of earthquake incidents - of mag 6.7 to greater - and the levels of the S&P 500 after one week, two weeks and 30 days. A chart of this last is presented. It also analyzes the effect for earthquakes occurring in the US.

**Comment by wel51x** [comment]
This also cleans up functionality to the Gold analysis previously submitted.

**Review by chrisluedtke — APPROVED** [review]
👍

**Pull request merged**
